# Kamal deployment workflow for Digital Ocean
# Deploys to nua.doctor domain using Kamal

name: Kamal Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # ensure only one deployment runs at a time
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Kamal
        run: gem install kamal

      - name: Deploy with Kamal (Placeholder)
        run: |
          echo "🚀 Kamal deployment temporarily disabled"
          echo "📋 Working on local Kamal setup first"
          echo "✅ GitHub Actions workflow ready for future deployment"
          # kamal deploy (disabled until local setup is working)
